### ISSUE TITLE
Fix entities anotations

### ISSUE THREAD

**Issue by ralexale** [Riwi-Meta/LOCAL_STORAGE_BACKEND#16]
## Hello @Alipser 

I'm checking your work and I found some mistakes, please remember not to use the @Data notation and the same with @Builder because it's not necessary. That's why you should replace @Data with @Getter,@Setter. Also, some entities need @AllArgsConstructor.

![image](https://github.com/Riwi-Meta/LOCAL_STORAGE_BACKEND/assets/59479109/234914dc-974c-4dc0-8377-0fa82845ec82)

**Comment by Alipser** [comment]
Done!

**Comment by ralexale** [comment]
Thank u !
